### ISSUE TITLE
does not work with react or next js

### ISSUE THREAD

**Issue by GX-TEC** [hmongouachon/rgbKineticSlider#17]

**Comment by jiayuwenn** [comment]
Have you solved it? I am also trying to integrate it into my next.js project.

**Comment by SohanR** [comment]
Could anyone possibly make it work in Next or React project? I tried in all possible ways but failed to implement this in Next js

**Comment by artimum1** [comment]
there is no solution but to import the script the HTML way,
and if you try to navigate through routing and head back again it will disappear.
my advice is that you create this effect with pixi js.
if you still want to use that one though you can simple import the script on the client side ( i don't recommend it )
` import Script from "next/script"
   . . . 
   <Script src="script.js"/>
`
