### ISSUE TITLE
Doesn't work on Google Chrome

### ISSUE THREAD

**Issue by ghost** [hmongouachon/rgbKineticSlider#4]
That's slider is cool! Unfortunately it doesn't work on google chrome, idk why but if I open the codepen's link on GC the page is white whether I check the link on Safari it works.
<img width="1398" alt="Schermata 2020-11-19 alle 11 57 39" src="https://user-images.githubusercontent.com/35579257/99657422-6ed9ec00-2a5e-11eb-9b51-562b8612092d.png">
![Schermata 2020-11-19 alle 11 57 19](https://user-images.githubusercontent.com/35579257/99657452-77322700-2a5e-11eb-81dc-b740399c7156.png)

**Comment by hmongouachon** [comment]
Hi Matteo,

Thanks for your feedback !
In fact the slider works well on chrome, but the assets used in the codepen
demo are loaded from my personal website which does not have https.
If you replace the images loaded in the demo by other one with https
protocol, it will work !

Hadrien




Le jeu. 19 nov. 2020 à 11:58, Matteo Subet <notifications@github.com> a
écrit :
